load('ext://uibutton', 'cmd_button')
load('ext://helm_resource', 'helm_resource', 'helm_repo')

# Welcome to nr-dashboard Tilt!
#   This Tiltfile is used to play with the Glance (the application
#   that powers the nr-dashboard) and configure it as quickly as
#   possible.
print("""
-----------------------------------------------------------------
  Welcome to nex·rpi Tilt!
    This Tiltfile is used to play with the nex·rpi project and
    configure it in a easy way.

    It uses Kustomize to manage Kubernetes resources through the
    `apps/*/live/dev` configurations.
-----------------------------------------------------------------
""".strip())

# Deploy Kubernetes resources using Kustomize
#   nex·rpi uses Kustomize to manage Kubernetes resources through the
#   `apps/*/live/dev` configurations.
#
#   In order to avoid deploying the whole project, Tilt will only
#   deploy what the end-user is working on.

# `nr-dashboard` namespace
def nr_dashboard():
    app_dir = '{tiltfile_dir}/apps/nr-dashboard'.format(tiltfile_dir=config.main_dir)

    nr_dashboard_yaml = kustomize('{app_dir}/live/dev'.format(app_dir=app_dir))
    nr_glance_configmaps = ['{}:configmap'.format(r["metadata"]["name"]) for r in decode_yaml_stream(nr_dashboard_yaml) if r["kind"] == "ConfigMap" and r["metadata"]["name"].startswith("glance-")]
    if len(nr_glance_configmaps) == 0:
        fail('⚠️ No glance configuration found. Please make sure to create one in the `configurations/glance.yaml` file.')

    watch_file('{app_dir}/live/dev/configurations/'.format(app_dir=app_dir))
    k8s_yaml(nr_dashboard_yaml)
    k8s_resource('glance',
                port_forwards=[8080],
                auto_init=False,
                objects=nr_glance_configmaps,
                labels=["nr-dashboard"])

    # Customise Tilt UI to syncronize Glance development configuration to the
    # production one
    cmd_button('sync_configuration',
        argv=[
            'cp',
            '--recursive',
            '{app_dir}/live/dev/configurations/'.format(app_dir=app_dir),
            '{app_dir}/live/production/'.format(app_dir=app_dir)
        ],
        icon_name='sync_alt',
        resource='glance',
        text='Sync configuration to production',
    )
nr_dashboard()

def resource_to_selector(resource):
    if "namespace" in resource["metadata"]:
        return "{}:{}:{}".format(
            resource["metadata"]["name"].replace(':', '\\:'),
            resource["kind"],
            resource["metadata"]["namespace"]
        )
    else:
        return "{}:{}".format(
            resource["metadata"]["name"].replace(':', '\\:'),
            resource["kind"]
        )

# test infrastructure
def infrastructure():
    # Step 0: Create the `crossplane-system` namespace
    k8s_yaml(encode_yaml({'apiVersion': 'v1', 'kind': 'Namespace', 'metadata': {'name': 'crossplane-system'}}))
    k8s_yaml(encode_yaml({'apiVersion': 'v1', 'kind': 'Namespace', 'metadata': {'name': 'localstack'}}))

    # Step 1: Deploy Crossplane, required to manage all cloud/3rd parties resources
    helm_repo('charts.crossplane.io', 'https://charts.crossplane.io/master/')
    helm_resource('crossplane', 'charts.crossplane.io/crossplane',
        namespace='crossplane-system',
        flags=[
            '--version=1.18.0-rc.0.61.ged4e659c',
            '--set=packageCache.sizeLimit=1Gi'
        ],
        auto_init=False, labels=["infrastructure"])

    # Step 3: Configure all the required providers
    k7e_dir = '{tiltfile_dir}/infrastructure/live/crossplane'.format(tiltfile_dir=config.main_dir)
    k7e_yaml = kustomize('{dir}/base/providers'.format(dir=k7e_dir))
    k7e_resources = [resource_to_selector(r) for r in decode_yaml_stream(k7e_yaml)]
    k8s_yaml(k7e_yaml)
    k8s_resource(
        new_name='crossplane-providers',
        resource_deps=['crossplane'],
        objects=k7e_resources,
        auto_init=False,
        labels=["infrastructure"]
    )

    # Step 2: Deploy LocalStack to simulate AWS services
    # NOTE: only few services are available in LocalStack, so some resources
    #       will not be supported in this Tiltfile.
    helm_repo('helm.localstack.cloud', 'https://helm.localstack.cloud')
    helm_resource('localstack', 'helm.localstack.cloud/localstack',
        namespace='localstack',
        port_forwards=[4566],
        auto_init=False, labels=["infrastructure"])

    # Add some buttons to stop all the services
    cmd_button('status_localstack',
        argv=[
            'localstack',
            'status',
            'services'
        ],
        icon_name='info',
        resource='localstack',
        text='LocalStack services status',
    )

    # Step 3: Deploy infrastructure resources
    # NOTE: This step is required because Tilts needs to know all CRDs (including the ones created by Crossplane)
    #       before applying the `k8s_resource` function.
    k7e_dir = '{tiltfile_dir}/infrastructure/live/crossplane'.format(tiltfile_dir=config.main_dir)
    k7e_yaml = kustomize('{dir}/dev'.format(dir=k7e_dir))
    k7e_resources = ["{}:{}".format(r["metadata"]["name"].replace(':', '\\:'), r["kind"].lower()) for r in decode_yaml_stream(k7e_yaml)]
    watch_file('{dir}/dev/'.format(dir=k7e_dir))
    watch_file('{dir}/base/'.format(dir=k7e_dir))
    k8s_yaml(k7e_yaml, allow_duplicates=True) # NOTE: allow_duplicates is required because providers are already deployed
    k8s_resource(
        new_name='crossplane-chezmoi.sh',
        resource_deps=['crossplane', 'crossplane-providers', 'localstack'],
        objects=k7e_resources,
        auto_init=False,
        labels=["infrastructure"]
    )

    # # Step 3: Group all resources under the `crossplane` resource
    # k8s_resource('crossplane',
    #     objects=["crossplane-system:namespace"] + k7e_resources,
    #     auto_init=False)
infrastructure()