---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: tailscale
    includeTemplates: true
    includeSelectors: true
  - pairs:
      app.kubernetes.io/part-of: tailscale
    includeTemplates: true

resources:
  - coredns-addons.configmap.yaml
  - ts-nameserver.config.yaml
  - ts-nameserver.rbac.yaml
  - ts-nameserver.workload.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: tailscale-system
      namespace: tailscale-system
    setRoleBindingSubjects: allServiceAccounts
    unsetOnly: true
