# trunk-ignore-all(checkov/CKV_K8S_21): the namespace is managed by Kustomize.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ts-nameserver-config
data:
  Corefile: |
    .:1053 {
      errors
      log
      health
      ready
      forward . 100.100.100.100 {
        max_concurrent 1000
      }
      cache 30
      reload 5s
      prometheus :9153
    }
