---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: infisical-database
  name: infisical-database
  namespace: infisical
spec:
  backup:
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      destinationPath: s3://cnpg-backups/amiya.akn.chezmoi.sh/infisical-database
      endpointURL: https://s3.chezmoi.sh:9000
      serverName: 01JY8VQQAMNV88S3HEF7DDW0DA # DRP::dst_ulid
      s3Credentials:
        accessKeyId:
          name: cnpg-s3-credentials
          key: access_key_id
        secretAccessKey:
          name: cnpg-s3-credentials
          key: access_secret_key
      wal:
        compression: bzip2
    retentionPolicy: 30d
  bootstrap:
    initdb:
      database: app
      owner: app
    # TODO: uncomment this after the first backup is taken
    # recovery:
    #   source: recoveryBackup
  description: PostgreSQL database dedicated to Infisical
  # TODO: uncomment this after the first backup is taken
  # externalClusters:
  #   - name: recoveryBackup
  #     barmanObjectStore:
  #       <<: *barmanObjectStore
  #       serverName: 000000000000000000000000 # DRP::src_ulid
  instances: 1
  storage:
    size: 5Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  labels:
    app.kubernetes.io/component: backup
  name: infisical-database
  namespace: infisical
spec:
  schedule: "@daily"
  backupOwnerReference: cluster
  cluster:
    name: infisical-database
