apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: sopsed-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./infisical.database.s3-credentials.yaml
