---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infisical

labels:
  - pairs:
      app.kubernetes.io/name: infisical
      app.kubernetes.io/part-of: infisical

resources:
  - infisical.database.yaml
  - namespace.yaml

generators:
  - ksops.generator.yaml
